/rs_camera:
  camera:
    ros__parameters:
      serial_no: 827112072702
      base_frame_id: rs_camera
      align_depth: true
      enable_pointcloud: true
      dense_pointcloud: true
      color0:
        enabled: true
        resolution: [640, 480]
        fps: 15
      depth0:
        enabled: true
        resolution: [640, 480]
        fps: 15
      infra1:
        enabled: false
        resolution: [640, 480]
        fps: 15
      infra2:
        enabled: false
        resolution: [640, 480]
        fps: 15
